// Organizations list
export const CLEAR_ORGANIZATIONS_CONTEXT = 'CLEAR_ORGANIZATIONS_CONTEXT';
export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const FETCH_ORGANIZATIONS_SUCCEEDED = 'FETCH_ORGANIZATIONS_SUCCEEDED';
export const FETCH_ORGANIZATIONS_FAILED = 'FETCH_ORGANIZATIONS_FAILED';

// Organization
export const CLEAR_ORGANIZATION_CONTEXT = 'CLEAR_ORGANIZATION_CONTEXT';
export const FETCH_ORGANIZATION = 'FETCH_ORGANIZATION';
export const FETCH_ORGANIZATION_SUCCEEDED = 'FETCH_ORGANIZATION_SUCCEEDED';
export const FETCH_ORGANIZATION_FAILED = 'FETCH_ORGANIZATION_FAILED';
export const CREATE_ORGANIZATION = 'CREATE_ORGANIZATION';
export const CREATE_ORGANIZATION_SUCCEEDED = 'CREATE_ORGANIZATION_SUCCEEDED';
export const CREATE_ORGANIZATION_FAILED = 'CREATE_ORGANIZATION_FAILED';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const UPDATE_ORGANIZATION_SUCCEEDED = 'UPDATE_ORGANIZATION_SUCCEEDED';
export const UPDATE_ORGANIZATION_FAILED = 'UPDATE_ORGANIZATION_FAILED';
export const REMOVE_ORGANIZATION = 'REMOVE_ORGANIZATION';
export const REMOVE_ORGANIZATION_SUCCEEDED = 'REMOVE_ORGANIZATION_SUCCEEDED';
export const REMOVE_ORGANIZATION_FAILED = 'REMOVE_ORGANIZATION_FAILED';

// Organization Users
export const CLEAR_ORGANIZATION_USERS_CONTEXT = 'CLEAR_ORGANIZATION_USERS_CONTEXT';
export const CLEAR_ORGANIZATION_USER_CONTEXT = 'CLEAR_ORGANIZATION_USER_CONTEXT';
export const FETCH_ORGANIZATION_USERS = 'FETCH_ORGANIZATION_USERS';
export const FETCH_ORGANIZATION_USERS_SUCCEEDED = 'FETCH_ORGANIZATION_USERS_SUCCEEDED';
export const FETCH_ORGANIZATION_USERS_FAILED = 'FETCH_ORGANIZATION_USERS_FAILED';
export const FETCH_ORGANIZATION_USER = 'FETCH_ORGANIZATION_USER';
export const FETCH_ORGANIZATION_USER_SUCCEEDED = 'FETCH_ORGANIZATION_USER_SUCCEEDED';
export const FETCH_ORGANIZATION_USER_FAILED = 'FETCH_ORGANIZATION_USER_FAILED';
export const CREATE_ORGANIZATION_USER = 'CREATE_ORGANIZATION_USER';
export const CREATE_ORGANIZATION_USER_SUCCEEDED = 'CREATE_ORGANIZATION_USER_SUCCEEDED';
export const CREATE_ORGANIZATION_USER_FAILED = 'CREATE_ORGANIZATION_USER_FAILED';
export const UPDATE_ORGANIZATION_USER = 'UPDATE_ORGANIZATION_USER';
export const UPDATE_ORGANIZATION_USER_SUCCEEDED = 'UPDATE_ORGANIZATION_USER_SUCCEEDED';
export const UPDATE_ORGANIZATION_USER_FAILED = 'UPDATE_ORGANIZATION_USER_FAILED';
export const REMOVE_ORGANIZATION_USER = 'REMOVE_ORGANIZATION_USER';
export const REMOVE_ORGANIZATION_USER_SUCCEEDED = 'REMOVE_ORGANIZATION_USER_SUCCEEDED';
export const REMOVE_ORGANIZATION_USER_FAILED = 'REMOVE_ORGANIZATION_USER_FAILED';
export const SEND_ORGANIZATION_USER_INVITE = 'SEND_ORGANIZATION_USER_INVITE';
export const SEND_ORGANIZATION_USER_INVITE_SUCCEEDED = 'SEND_ORGANIZATION_USER_INVITE_SUCCEEDED';
export const SEND_ORGANIZATION_USER_INVITE_FAILED = 'SEND_ORGANIZATION_USER_INVITE_FAILED';

// Organization Airlines
export const FETCH_ORGANIZATION_AIRLINES = 'FETCH_ORGANIZATION_AIRLINES';
export const FETCH_ORGANIZATION_AIRLINES_SUCCEEDED = 'FETCH_ORGANIZATION_AIRLINES_SUCCEEDED';
export const FETCH_ORGANIZATION_AIRLINES_FAILED = 'FETCH_ORGANIZATION_AIRLINES_FAILED';

// Organization Airline Account
export const CLEAR_AIRLINE_CONTEXT = 'CLEAR_AIRLINE_CONTEXT';
export const FETCH_AIRLINE_ACCOUNT = 'FETCH_AIRLINE_ACCOUNT';
export const FETCH_AIRLINE_ACCOUNT_SUCCEEDED = 'FETCH_AIRLINE_ACCOUNT_SUCCEEDED';
export const FETCH_AIRLINE_ACCOUNT_FAILED = 'FETCH_AIRLINE_ACCOUNT_FAILED';
export const UPDATE_AIRLINE_ACCOUNT = 'UPDATE_AIRLINE_ACCOUNT';
export const UPDATE_AIRLINE_ACCOUNT_SUCCEEDED = 'UPDATE_AIRLINE_ACCOUNT_SUCCEEDED';
export const UPDATE_AIRLINE_ACCOUNT_FAILED = 'UPDATE_AIRLINE_ACCOUNT_FAILED';

// Organization Airline Account Air Waybills
export const CREATE_AIRLINE_ACCOUNT_AWBS = 'CREATE_AIRLINE_ACCOUNT_AWBS';
export const CREATE_AIRLINE_ACCOUNT_AWBS_SUCCEEDED = 'CREATE_AIRLINE_ACCOUNT_AWBS_SUCCEEDED';
export const CREATE_AIRLINE_ACCOUNT_AWBS_FAILED = 'CREATE_AIRLINE_ACCOUNT_AWBS_FAILED';
export const FETCH_AIRLINE_ACCOUNT_AWBS = 'FETCH_AIRLINE_ACCOUNT_AWBS';
export const FETCH_AIRLINE_ACCOUNT_AWBS_SUCCEEDED = 'FETCH_AIRLINE_ACCOUNT_AWBS_SUCCEEDED';
export const FETCH_AIRLINE_ACCOUNT_AWBS_FAILED = 'FETCH_AIRLINE_ACCOUNT_AWBS_FAILED';
export const CREATE_AIRLINE_ACCOUNT_AWB = 'CREATE_AIRLINE_ACCOUNT_AWB';
export const CREATE_AIRLINE_ACCOUNT_AWB_SUCCEEDED = 'CREATE_AIRLINE_ACCOUNT_AWB_SUCCEEDED';
export const CREATE_AIRLINE_ACCOUNT_AWB_FAILED = 'CREATE_AIRLINE_ACCOUNT_AWB_FAILED';
export const REMOVE_AIRLINE_ACCOUNT_AWB = 'REMOVE_AIRLINE_ACCOUNT_AWB';
export const REMOVE_AIRLINE_ACCOUNT_AWB_SUCCEEDED = 'REMOVE_AIRLINE_ACCOUNT_AWB_SUCCEEDED';
export const REMOVE_AIRLINE_ACCOUNT_AWB_FAILED = 'REMOVE_AIRLINE_ACCOUNT_AWB_FAILED';
