export const CLEAR_SETTINGS_CONTEXT = 'CLEAR_SETTINGS_CONTEXT';
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_SUCCEEDED = 'UPDATE_SETTINGS_SUCCEEDED';
export const UPDATE_SETTINGS_FAILED = 'UPDATE_SETTINGS_FAILED';
export const CLEAR_USER_PASSWORD_CONTEXT = 'CLEAR_USER_PASSWORD_CONTEXT';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const UPDATE_USER_PASSWORD_SUCCEEDED = 'UPDATE_USER_PASSWORD_SUCCEEDED';
export const UPDATE_USER_PASSWORD_FAILED = 'UPDATE_USER_PASSWORD_FAILED';
